usb: xhci-plat: Don't include xhci.h
commit 4a237d55446ff67655dc3eed2d4a41997536fc4c upstream.

The xhci_plat.h should not need to include the entire xhci.h header.
This can cause redefinition in dwc3 if it selectively includes some xHCI
definitions. This is a prerequisite change for a fix to disable suspend
during initialization for dwc3.

Cc: stable@vger.kernel.org
Signed-off-by: Thinh Nguyen <Thinh.Nguyen@synopsys.com>
Link: https://lore.kernel.org/r/310acfa01c957a10d9feaca3f7206269866ba2eb.1713394973.git.Thinh.Nguyen@synopsys.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

------------------------------------------------------------------------------------------------------------------------
usb: dwc3: imx8mp: fix undeclared variable error

w.r.t upstream kernel commit (usb: xhci-plat: Don't include xhci.h)
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.15.y&id=f78ff8825eb8c07b7cec119548fd24aa5061fc5c

build failure:
| <build_dir>/tmp/work-shared/imx8mpevk-flex/kernel-source/drivers/usb/dwc3/dwc3-imx8mp.c:121:19: error: 'XHCI_MISSING_CAS' undeclared here (not in a function)
|   121 |         .quirks = XHCI_MISSING_CAS |
|       |                   ^~~~~~~~~~~~~~~~
| <build-dir>/tmp/work-shared/imx8mpevk-flex/kernel-source/drivers/usb/dwc3/dwc3-imx8mp.c:122:19: error: 'XHCI_SKIP_PHY_INIT' undeclared here (not in a function)
|   122 |                   XHCI_SKIP_PHY_INIT,
|       |                   ^~~~~~~~~~~~~~~~~~
| make[3]: *** [<build_dir>/tmp/work-shared/imx8mpevk-flex/kernel-source/scripts/Makefile.build:289: drivers/usb/dwc3/dwc3-imx8mp.o] Error 1
| make[2]: *** [<build_dir>/tmp/work-shared/imx8mpevk-flex/kernel-source/scripts/Makefile.build:552: drivers/usb/dwc3] Error 2

to fix this build error of undeclared variable include xhci.h in dwc3-imx8mp.c

Signed-off-by: Prajwal <prajwal.gowda-hm.ext@siemens.com>